#!/bin/bash

#for seting up simple http server

uslov=$(ip -f inet addr show tun0 2>&1)

 



if [[ $uslov == *"does not exist."* ]] ; then
	ip -f inet addr show eth0 | grep -Po "inet \K[\d.]+";
else
	ip -f inet addr show tun0 | grep -Po "inet \K[\d.]+";
fi

echo $PWD
sudo python3 -m http.server 80
